---
name: Release Library

on:
  workflow_call:
    inputs:
      submodules:
        description: Whether to checkout submodules. Use `true` to checkout submodules or `recursive` to recursively checkout submodules -- see https://github.com/actions/checkout
        required: false
        type: string
        default: false
      toolchain:
        description: Rust toolchain specification
        type: string
        default: stable
      disable-semantic-release-cargo:
        description: Disable semantic-release-cargo in your release flow. Only takes effect if the action semantic-release config is used.
        type: boolean
        default: false
      disable-semantic-release-git:
        description: Disable @semantic-release/git in your release flow. Only takes effect if the action semantic-release config is used.
        type: boolean
        default: true
    secrets:
      cargo-registry-token:
        description: API token for writing to your cargo registry

# Only allow one release workflow to execute at a time, since each release
# workflow uses shared resources (git tags, package registries)
concurrency:
  group: ${{ github.workflow }}

env:
  RUST_BACKTRACE: 1

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Release
        uses: casbin-rs/semantic-release-action-rust/semantic-release-library@master
        with:
          toolchain: ${{ inputs.toolchain }}
          disable-semantic-release-cargo: ${{ inputs.disable-semantic-release-cargo }}
          disable-semantic-release-git: ${{ inputs.disable-semantic-release-git }}
          cargo-registry-token: ${{ secrets.cargo-registry-token }}
          submodules: ${{ inputs.submodules }}
